import type { Metadata } from "next";
import "./globals.css";
import { Header } from '@/components/Header';
import MainFooter from '@/components/MainFooter';

import { ChatProvider } from '@/context/ChatContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChatProvider 
          initialRAG={null}
          initialContent={null}
        >
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-grow container mx-auto px-4 py-8">
              {children}
            </main>
            <MainFooter />
          </div>
        </ChatProvider>
      </body>
    </html>
  );
}
